version: '3.5'

services:
  api:
    build: ./
    
    ports:
      - 80:8000


    env_file:
      - ./.env
    
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        python manage.py runserver 0.0.0.0:8000 --noreload
        "


    networks:
      - server-net
    volumes:
      - ./:/hacker_news
      - static_vol:/hacker_news/static
      

    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - server-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    env_file:
      - ./.env
    


networks:
  server-net:

volumes:
  postgres_data:
  static_vol:
 
